sudo: false
language: node_js
node_js:
  - "0.10.36"
before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - export PATH="$HOME/.meteor:$PATH"
  - meteor update
  - npm install -g spacejam

script: "spacejam test-packages ./"